export const url = {
  // 获取分类商品的列表
  getCategoriedProducts: '/shop/category/show/ui/getCategoriedProducts.do',
  // 获取购买商品列表
  getRecordList: '/shop/product/show/ui/getRecordList.do',
  // 是否用户名已存在
  isExistUserName: '/shop/member/show/ui/isExistUserName.do',
  // 用户登录接口
  memberLogin: '/shop/member/show/ui/memberLogin.do',
  // 用户注册接口
  createMember: '/shop/member/show/ui/createMember.do',
  // 商品购买接口
  saveRecordList: '/shop/product/show/ui/saveRecordList.do',
  // 更新订单状态的接口
  alterStatus: '/shop/product/show/ui/alterStatus.do',
  // 修改会员信息接口
  modifyBasicInfo: '/shop/member/show/ui/modifyBasicInfo.do',
  // 修改密码接口
  modifyPassword: '/shop/member/show/ui/modifyPassword.do',
  // 获取三方登陆的会员信息接口
  getMemberById: '/shop/member/show/ui/getMemberById.do',
  // 获取配送地址列表
  getAddresses: '/shop/product/show/ui/getAddresses.do',
  // 保存配送地址
  saveAddresses: '/shop/product/show/ui/saveAddresses.do',
  // 删除配送地址
  deleteAddresses: '/shop/product/show/ui/deleteAddresses.do',
  // 获取会员信息
  getBasicInfoList: '/shop/member/show/ui/getBasicInfoList.do'
};
